definitions:
  check_form.LoginForm:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/menu/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true,"returnCode":200,"msg":"OK",data":{}}'
          schema:
            type: string
      summary: 获取权限功能列表
  /v1/user/login:
    post:
      parameters:
      - description: 用户登录接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/check_form.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":true,"returnCode":200,"msg":"OK",data":{}}'
          schema:
            type: string
      summary: 用户登录
swagger: "2.0"
